# Alternative serverless configuration using container images
# Use this if Lambda layers approach doesn't work for heavy dependencies

service: flr-slack-bot-container

frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  timeout: 900
  memorySize: 3008
  ecr:
    images:
      flr-bot:
        path: ./
        file: Dockerfile
        platform: linux/amd64
  
  environment:
    S3_BUCKET_NAME: ${self:custom.bucketName}
    STAGE: ${self:provider.stage}
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: "arn:aws:s3:::${self:custom.bucketName}/*"
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource: "arn:aws:s3:::${self:custom.bucketName}"

custom:
  bucketName: flr-reports-${self:provider.stage}-${aws:accountId}

functions:
  slackBot:
    image:
      name: flr-bot
    events:
      - http:
          path: /slack/flr-report
          method: post
          cors: true
    environment:
      S3_BUCKET_NAME: ${self:custom.bucketName}

resources:
  Resources:
    ReportsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        VersioningConfiguration:
          Status: Enabled
        LifecycleConfiguration:
          Rules:
            - Id: DeleteReportsAfter7Days
              Status: Enabled
              ExpirationInDays: 7
              NoncurrentVersionExpirationInDays: 1

  Outputs:
    SlackWebhookUrl:
      Description: "Slack webhook URL for /flr-report command"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api."
            - ${self:provider.region}
            - ".amazonaws.com/"
            - ${self:provider.stage}
            - "/slack/flr-report"